/**
 * The art bible, rendered from the brief, the references and the rulings.
 *
 * The document is generated, so nobody edits it: an art rule that was typed
 * straight into prose has no reference behind it and no field to check, which
 * is the state this plugin exists to end. Change a ruling and run `art.bible`.
 *
 * The order of the sections is the order the work happens in — brief, then
 * references, then what they agree on, then the rulings drawn from that. A
 * reader who stops after two sections has still read the evidence.
 */

const table = (headings, rows) => [
  `| ${headings.join(' | ')} |`,
  `|${headings.map(() => '---').join('|')}|`,
  ...rows.map(row => `| ${row.join(' | ')} |`)
].join('\n')

/** A source is a link only when it is one. A hand-supplied file has no URL to point at. */
const sourceCell = source =>
  (/^https?:\/\//i.test(source || '') ? `[link](${source})` : (source || 'supplied by hand'))

/**
 * One ruling, as a heading and its evidence.
 *
 * Every ruling prints how it is checked, because that is the only thing
 * separating a fact from a preference here, and a reader must never have to
 * guess which one they are being handed.
 */
function ruling(entry) {
  const lines = [`### ${entry.says}`, '']
  if (entry.why) lines.push(entry.why, '')
  if (entry.check === 'measured') {
    lines.push(`**Checked:** \`${entry.field}\` ${wantsAsWords(entry.wants)}. `
      + 'Run `art.check` against a frame.')
  } else if (entry.check === 'derived') {
    lines.push(`**Derived.** It follows from the fact above, not from a picture.${
      entry.enforcedBy ? ` Enforced by ${entry.enforcedBy}.` : ' Nothing enforces it automatically.'}`)
  } else {
    lines.push('**Judged, not measured.** No number decides this one. '
      + 'Run `art.compare` and read the two frames side by side.')
  }
  if (entry.from?.length) lines.push('', `**From:** ${entry.from.map(name => `\`${name}\``).join(', ')}`)
  return lines.join('\n')
}

function wantsAsWords(wants = {}) {
  const parts = []
  if (typeof wants.min === 'number') parts.push(`at least ${wants.min}`)
  if (typeof wants.max === 'number') parts.push(`at most ${wants.max}`)
  if (typeof wants.near === 'number') parts.push(`near ${wants.near} ± ${wants.within ?? 0.05}`)
  return parts.length ? parts.join(', ') : 'no bound set'
}

export function renderBible({ brief, references, agreed, rulings, legacy, siblings = [] }) {
  const out = []
  const subject = brief?.subject || 'this project'

  out.push(`# The art bible for ${subject}`, '')
  out.push('Generated by the Art Direction plugin from `brief.json`, `references/` and'
    + ' `rulings.json` in this directory. Do not edit this file — edit those and run'
    + ' `art.bible`.', '')

  // A reader who does not know the other subjects exist will apply this one's
  // rules to work it does not cover.
  if (siblings.length) {
    out.push(`This covers **${subject}** only. The other subjects with their own bible: `
      + siblings.map(name => `\`${name}\``).join(', ') + '.', '')
  }

  if (legacy) {
    out.push(`> An older hand-written art document is stored at \`${legacy.path}\`. `
      + 'Where the two disagree, this one is right: every rule here names the reference '
      + 'and the measurement behind it. Move anything still worth keeping across as a '
      + 'ruling, then delete it.', '')
  }

  if (brief?.reads) out.push('## What it has to communicate', '', brief.reads, '')
  if (brief?.camera) out.push('## The camera that sees it', '', brief.camera, '')
  if (brief?.questions?.length) {
    out.push('## The questions this direction answers', '',
      ...brief.questions.map(question => `- ${question}`), '')
  }

  out.push('## The references', '')
  if (!references.length) {
    out.push('None yet. Nothing below this line has evidence behind it.', '')
  } else {
    out.push(table(['file', 'answers', 'source'], references.map(entry => [
      `\`${entry.file}\``, entry.answers || '—', sourceCell(entry.source)
    ])), '')
  }

  if (agreed?.agreed?.length) {
    out.push('## What the references agree on', '',
      `Measured across ${agreed.references} references. A ruling may quote any of these.`, '',
      table(['field', 'low', 'median', 'high'], agreed.agreed.map(entry =>
        [`\`${entry.field}\``, entry.low, entry.median, entry.high])), '')
    if (agreed.palette?.length) {
      out.push('The colours they are made of: ' + agreed.palette.map(colour => `\`${colour}\``).join(' '), '')
    }
  }

  if (agreed?.split?.length) {
    out.push('## Where the references disagree', '',
      'Each of these is a decision nobody has made yet. Averaging them would produce a look'
      + ' none of the references has.', '',
      table(['field', 'low', 'high', 'spread'], agreed.split.map(entry =>
        [`\`${entry.field}\``, entry.low, entry.high, entry.spread])), '')
  }

  const of = kind => rulings.filter(entry => entry.check === kind)
  const measured = of('measured')
  const derived = of('derived')
  const judged = of('judged')

  out.push('## The rulings', '')
  if (!rulings.length) out.push('None yet.', '')
  if (measured.length) {
    out.push('These have a number, and `art.check` tests every one of them against a frame.', '')
    out.push(...measured.map(ruling), '')
  }
  // Before the judged ones: these are the hardest constraints in the document,
  // and a reader who stops early should have met them.
  if (derived.length) {
    out.push('## Rulings that follow from the format', '',
      'No reference produced these and no frame tests them. They follow by arithmetic'
      + ' from the camera, the screen and the unit scale, so they hold whatever the'
      + ' style is and they outrank anything above that disagrees.', '')
    out.push(...derived.map(ruling), '')
  }
  if (judged.length) {
    out.push('## Rulings that need an eye', '',
      'No measurement decides these. Check them with `art.compare` and a forced'
      + ' choice between two frames, never with a score.', '')
    out.push(...judged.map(ruling), '')
  }

  out.push('## Checking the game against this', '', [
    '```sh',
    'node bin/engine.mjs run see.capture \'{"marks":false,"name":"look"}\'',
    'node bin/engine.mjs run art.check \'{"frame":"agent-runs/see/look.png"}\'',
    'node bin/engine.mjs run art.compare \'{"reference":"<file>","frame":"agent-runs/see/look.png"}\'',
    '```'
  ].join('\n'), '')

  return out.join('\n')
}
