/** Each entry is an independent data block. Tags describe compatibility, not class locks. */
export const items = {
  pouch: { name: 'Patched Pouch', mark: 'p', footprint: [1, 1], tags: ['storage', 'scavenging'], storage: { columns: 1 }, abilities: [],
    description: 'Attach to the right edge: a full-height 1-column pouch. Put items inside. Empty it before detaching.' },
  pack: { name: 'Worn Pack', mark: 'P', footprint: [1, 2], tags: ['storage', 'scavenging'], storage: { columns: 2 }, abilities: [],
    description: 'Attach to the right edge: a full-height 2-column pack. Put items inside; chain another pack to its right.' },
  dagger: { name: 'Rusty Dagger', mark: 'D', footprint: [1, 2], tags: ['weapon', 'blade', 'combat'], stats: { damage: 2 }, abilities: ['strike'],
    description: 'Deal 2 damage. Uses any prepared coating on its next strike.' },
  sword: { name: 'Iron Sword', mark: 'I', footprint: [1, 3], tags: ['weapon', 'blade', 'combat'], stats: { damage: 5 }, abilities: ['strike'],
    description: 'Deal 5 damage. Stronger, but needs a full column.' },
  venom: { name: 'Venom Vial', mark: 'V', footprint: [1, 1], tags: ['alchemy', 'growth'], abilities: ['coat'],
    description: 'Weapon touching the right edge: add 2 Poison to its next strike. Once per cycle.' },
  stone: { name: 'Whetstone', mark: 'W', footprint: [1, 1], tags: ['tool', 'combat'], abilities: ['sharpen'],
    description: 'Weapon touching the right edge: +2 damage on its next strike. Once per cycle.' },
  tooth: { name: 'Ward Tooth', mark: 'T', footprint: [1, 1], tags: ['relic', 'hunger'], abilities: ['venomGuard'],
    description: 'When an edge-adjacent weapon applies Poison, gain 2 guard. Once per cycle.' },
  buckler: { name: 'Buckler', mark: 'B', footprint: [2, 2], tags: ['armour', 'combat'], stats: { guard: 3 }, abilities: ['protect'],
    description: 'Gain 3 guard this cycle. A wide shield occupies four cells.' },
  salve: { name: 'Herbal Salve', mark: '+', footprint: [1, 1], tags: ['herb', 'growth'], stats: { heal: 2 }, abilities: ['mend'],
    description: 'Heal 2. One charge, refilled each cycle.' },
  hungryTooth: { name: 'Hungry Tooth', mark: 'H', footprint: [1, 1], tags: ['relic', 'hunger'], abilities: ['feed'],
    description: 'An edge-adjacent weapon dealing damage gives your recruit 1 Hunger. Once per cycle.' },
  bloodCup: { name: 'Blood Cup', mark: 'C', footprint: [1, 1], tags: ['relic', 'hunger'], abilities: ['drink'],
    description: 'Spend 3 of your recruit’s Hunger to heal 6. Waits if health is full.' },
  salt: { name: 'Purifying Salt', mark: 'S', footprint: [1, 1], tags: ['alchemy', 'scholarship'], abilities: ['cleanse'],
    description: 'Remove up to 3 Poison from your recruit each cycle.' },
  banner: { name: 'Torn Banner', mark: 'F', footprint: [1, 2], tags: ['relic', 'combat'], abilities: [],
    auras: [{ target: { kind: 'adjacentItems', tags: ['weapon'], ownerOnly: true }, stat: 'damage', amount: 1 }],
    description: 'While equipped, every edge-adjacent weapon has +1 damage.' },
  echo: { name: 'Echo Chime', mark: 'E', footprint: [1, 1], tags: ['relic', 'scholarship'], abilities: ['echo'],
    description: 'Activate the weapon directly below once more. Once per combat.' },
  sprig: { name: 'Living Sprig', mark: 'G', footprint: [1, 1], tags: ['herb', 'growth'], abilities: ['regrow'],
    description: 'Gain 2 Regeneration once per combat. Heals at cycle start, then loses one stack.' }
}
