/** A landscape notebook keeps the saved library, editable concept and test feedback distinct. */
import { art, artLibrary, artChoices, artCategories } from '../art.js'
import { kinds, families, statuses } from './model.js'
import { vocabulary } from '../../grid-game/api.js'
import { catalog } from '../catalog.js'
import { escape } from '../inspection.js'
export function crafterView(kit, state) {
  const draft = state.draft, rule = state.rule
  const button = (label, action, value) => kit.button(label, { action, value })
  const select = (label, action, value, options) => kit.select(label, { action, value, options })
  const text = (label, action, value) => kit.textInput(label, { action, value })
  const area = (label, action, value, rows = 4) => kit.textArea(label, { action, value, rows })
  const concept = () => `<div class="craft-identity">${art(kit, draft.icon, draft.name)}<div>${text('Name', 'craftName', draft.name)}${select('Power family', 'craftFamily', draft.family, families)}</div></div>${button('Choose portrait / icon', 'craftChooseArt')}${area('What is this? Description / NPC dialogue', 'craftDescription', draft.description, 3)}${area('Raw ideas for the AI — rough notes are welcome', 'craftNotes', draft.notes, 5)}${draft.kind === 'item' ? `<div class="craft-row">${select('Grid width', 'craftWidth', String(draft.definition.footprint[0]), ['1', '2', '3'])}${select('Grid height', 'craftHeight', String(draft.definition.footprint[1]), ['1', '2', '3'])}</div>` : kit.slider('Health', { action: 'craftHealth', value: draft.definition.maxHealth, min: 1, max: 60, step: 1 })}`
  const rules = () => `${draft.kind !== 'item' ? `<h3>Equipment</h3>${select('Add an item to the loadout', 'craftGear', '', [{ value: '', label: 'Choose equipment…' }, ...Object.keys(catalog.items)])}${draft.definition.loadout.map((item, index) => `<div class="craft-saved">${art(kit, item.type)}<span>${escape(catalog.items[item.type].name)} @ ${item.position}</span>${button('Remove', 'craftRemoveGear', index)}</div>`).join('')}` : ''}<p>Add small rules. Each means: when → target → effect. Advanced grants, auras, costs and loadouts can be edited through JSON.</p>${(draft.definition.abilities ?? []).map((ability, index) => `<section class="craft-rule"><code>${escape(typeof ability === 'string' ? ability : `${ability.trigger.event} → ${ability.target.kind} → ${ability.effects.map(effect => effect.type + ' ' + JSON.stringify(effect.amount ?? '')).join(', ')}`)}</code>${button('Remove', 'craftRemoveRule', index)}</section>`).join('') || '<p>No active rules.</p>'}<div class="craft-fields">${select('When', 'craftRuleTrigger', rule.trigger, vocabulary.triggers)}${select('Target', 'craftRuleTarget', rule.target, ['enemy', 'owner', 'self', 'adjacentItems', 'right', 'left', 'up', 'down', 'eventTarget'])}${select('Effect', 'craftRuleEffect', rule.effect, ['damage', 'heal', 'guard', 'applyStatus', 'removeStatus', 'modifyStat', 'resource', 'triggerItem'])}${kit.slider('Amount', { action: 'craftRuleAmount', value: rule.amount, min: -10, max: 20, step: 1 })}${select('Status', 'craftRuleStatus', rule.status, statuses)}${select('Duration', 'craftRuleDuration', rule.duration, vocabulary.durations)}${text('Stat name', 'craftRuleStat', rule.stat)}${text('Resource name', 'craftRuleResource', rule.resource)}${select('Limit per cycle (0 = unlimited)', 'craftRuleLimit', String(rule.limit), ['0', '1', '2', '3'])}</div>${button('Add rule', 'craftAddRule')}`
  const test = () => `${button('Run 12-cycle test', 'craftTest')}${state.test ? `<p>${escape(state.test.note)}</p><div class="craft-identity">${art(kit, draft.icon, draft.name)}<p><strong>${escape(state.test.winner === 'subject' ? 'Draft wins' : state.test.winner === 'opponent' ? 'Opponent wins' : 'Stalemate')}</strong><br>${state.test.cycles} cycles · Draft HP ${state.test.subjectHealth} · Opponent HP ${state.test.opponentHealth}</p></div><details><summary>Test grid / starting data</summary><pre>${escape(JSON.stringify(state.test.initial.items, null, 2))}</pre></details><ol class="craft-log">${state.test.events.map(event => `<li>${escape(event)}</li>`).join('') || '<li>No effects fired. Check triggers and targets.</li>'}</ol>` : '<p>Test this concept with the same rules as the game. Your company and loot stay untouched. A social NPC with no combat abilities will not attack.</p>'}`
  const exchange = () => `<p>Use AI brief → copy to ChatGPT → paste its JSON reply → Import JSON → test and save. This prototype has no connected AI service.</p><div class="craft-row">${button('AI brief', 'craftBrief')}${button('Export JSON', 'craftExport')}${button('Copy text', 'craftCopy')}${button('Import JSON', 'craftImport')}</div>${area('Brief or JSON — long-press to select / copy', 'craftTransfer', state.transfer, 14)}`
  const gallery = () => {
    const choices = artChoices(state.gallery), selected = artLibrary.find(entry => entry.id === draft.icon)
    return `<div class="craft-art-controls">${select('Show', 'craftArtKind', state.gallery.kind, [{ value: 'all', label: 'All art' }, { value: 'item', label: 'Items' }, { value: 'portrait', label: 'Portraits' }])}${select('Group', 'craftArtCategory', state.gallery.category, [{ value: 'all', label: 'All groups' }, ...artCategories(state.gallery.kind)])}${text('Search art', 'craftArtQuery', state.gallery.query)}</div><div class="craft-art-summary"><p>${choices.length} choices · Selected: <strong>${escape(selected?.label ?? draft.icon)}</strong><br>Tap an image, then Save concept.</p>${button('Done', 'craftTab', 'concept')}</div><div class="craft-art-grid">${choices.map(entry => kit.target(`${art(kit, entry.id)}<span>${escape(entry.label)}</span>`, { as: 'button', action: 'craftIcon', value: entry.id, label: entry.label, class: 'craft-art-tile', attributes: { type: 'button', 'aria-label': entry.label, 'aria-pressed': String(entry.id === draft.icon), 'data-key': entry.id } })).join('') || '<p>No matches. Clear search or choose another group.</p>'}</div>`
  }
  const panels = { concept, art: gallery, rules, test, exchange }
  return `<main class="crafter-game"><header><strong>THE SCRIBE'S BENCH</strong><div>${button('Save concept', 'craftSave')}${button('Back to game', 'craftClose')}</div></header><p class="craft-status" role="status">${escape(state.warning || state.message || 'Draft items, characters, enemies and tavern NPCs. Save on this device; export JSON as a backup.')}${state.dirty ? ' · UNSAVED' : ''}</p><section class="craft-body${state.tab === 'art' ? ' art-open' : ''}"><aside><h3>NEW CONCEPT</h3><div class="craft-new">${kinds.map(kind => button('+ ' + kind, 'craftNew', kind)).join('')}</div>${select('Copy an existing item', 'craftTemplate', '', [{ value: '', label: 'Choose a template…' }, ...Object.keys(catalog.items)])}<h3>SAVED CONCEPTS</h3>${state.library.drafts.map(saved => `<div class="craft-saved">${art(kit, saved.icon)}${button(saved.name + ' · ' + saved.kind, 'craftLoad', saved.id)}</div>`).join('') || '<p>No saved concepts yet.</p>'}</aside><article>${kit.tabs([{ value: 'concept', label: 'Concept' }, { value: 'art', label: 'Art' }, { value: 'rules', label: 'Rules' }, { value: 'test', label: 'Test' }, { value: 'exchange', label: 'AI / JSON' }], { action: 'craftTab', value: state.tab })}<div class="craft-page" data-key="craft:${draft.id}:${state.tab}">${panels[state.tab]()}</div></article></section></main>`
}
